spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${PASS-DB}
    url: ${URL-DB}
    username: ${USER-DB}
  jpa:
    show:
      sql: ${SHOW-SQL}
  flyway:
    baselineOnMigrate: true